title: "Yuexuan Li's Personal Website"
author: "Yuexuan Li"
description: ""
permalink: /:title/
lang: "en"
excerpt_separator: "\n\n\n"
date_format: ""

# Layout

show_excerpts: true        # show article excerpts on the home page
show_frame: true           # adds a gray frame to the site
show_sidebar: true        # show a sidebar instead of the usual header
minimal: false             # use a dark header

# Menu

navigation:                # accepts {file, title, url, icon, sidebaricon}
  - {file: "index.html",title: "Home"}
  - {file: "index2.html",title: "Research"}
  - {file: "README.md", title: "Publication"}
  

external:                  # shows a footer with social links - for available icons see fontawesome.com/icons
  - {title: Google Scholar, icon: graduation-cap, url: "https://scholar.google.com/citations?user=ZpPKaNoAAAAJ&hl=en"}
  - {title: Github, icon: github, url: "https://github.com/yxl95/"}
  - {title: Twitter, icon: twitter, url: "https://twitter.com/yuexuan_li"}

comments:
#  disqus_shortname: ""    # see https://disqus.com/
#  isso_domain: ""         # see https://posativ.org/isso/

plugins:
 - jekyll-feed
